//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2009/11/edm", IsNullable=false)]
public partial class PropertyRef {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2009/11/edm", IsNullable=false)]
public partial class End {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Role;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Multiplicity;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntitySet;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2009/11/edm", IsNullable=false)]
public partial class Schema {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityType")]
    public SchemaEntityType[] EntityType;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Association")]
    public SchemaAssociation[] Association;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityContainer")]
    public SchemaEntityContainer[] EntityContainer;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Namespace;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Alias;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2009/02/edm/annotation")]
    public string UseStrongSpatialTypes;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PropertyRef", typeof(PropertyRef), IsNullable=false)]
    public PropertyRef[] Key;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property")]
    public SchemaEntityTypeProperty[] Property;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NavigationProperty")]
    public SchemaEntityTypeNavigationProperty[] NavigationProperty;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityTypeProperty {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Nullable;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2009/02/edm/annotation")]
    public string StoreGeneratedPattern;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaxLength;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FixedLength;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Unicode;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Precision;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityTypeNavigationProperty {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Relationship;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromRole;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToRole;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaAssociation {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("End")]
    public End[] End;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferentialConstraint")]
    public SchemaAssociationReferentialConstraint[] ReferentialConstraint;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaAssociationReferentialConstraint {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Principal")]
    public SchemaAssociationReferentialConstraintPrincipal[] Principal;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Dependent")]
    public SchemaAssociationReferentialConstraintDependent[] Dependent;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaAssociationReferentialConstraintPrincipal {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyRef")]
    public PropertyRef[] PropertyRef;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Role;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaAssociationReferentialConstraintDependent {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyRef")]
    public PropertyRef[] PropertyRef;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Role;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityContainer {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntitySet")]
    public SchemaEntityContainerEntitySet[] EntitySet;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AssociationSet")]
    public SchemaEntityContainerAssociationSet[] AssociationSet;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/ado/2009/02/edm/annotation")]
    public string LazyLoadingEnabled;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityContainerEntitySet {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string EntityType;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
public partial class SchemaEntityContainerAssociationSet {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("End")]
    public End[] End;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Association;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/ado/2009/11/edm")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ado/2009/11/edm", IsNullable=false)]
public partial class NewDataSet {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("End", typeof(End))]
    [System.Xml.Serialization.XmlElementAttribute("PropertyRef", typeof(PropertyRef))]
    [System.Xml.Serialization.XmlElementAttribute("Schema", typeof(Schema))]
    public object[] Items;
}
